### ISSUE TITLE
How fast  change pin mode (out to in and back)

### ISSUE THREAD

**Issue by icupken** [warthog618/gpiocdev-rs#13]
Hello! I found your lib is awesome! But have a problem:
I have cpp code on wiringOP
```
pinMode(pin, OUTPUT);
digitalWrite(pin, LOW);
delayMicroseconds(480);

pinMode(pin, INPUT);
delayMicroseconds(60);

response = digitalRead(pin);
delayMicroseconds(410);
```

How can I quickly change the output type? such as pinMode

**Comment by warthog618** [comment]
Use the [Request::reconfigure()](https://docs.rs/gpiocdev/0.6.1/gpiocdev/request/struct.Request.html#method.reconfigure) method to change the configuration of the requested lines.
You can get the current configuration using the Request::config() method, then mutate that as required before passing it into reconfigure().

Maybe I should add some examples for that.  And perhaps some reconfigure benchmarks as well.  I'll add that to the todo list.

Wrt update rates, there are too many variables to account for, so I suggest you benchmark on your hardware.  IIRC, WiringPi and WiringOP access the hardware directly so that is probably a fair bit faster, but opens you up to contention issues that the kernel protects you from.  The kernel GPIO uAPI has a userspace/kernel context switch that can't be avoided and adds overhead.
For reference, on a Pi4 requesting a line takes about 80usec, and changing an output value takes 
about 2usec.  I would guess an input/output reconfigure() would be somewhere between the two, but I don't have any benchmarks handy to prove that.

**Comment by warthog618** [comment]
Wrt an example, take a look at the [reconfigure() test](https://github.com/warthog618/gpiocdev-rs/blob/master/lib/tests/request.rs#L1541).

**Comment by warthog618** [comment]
I've added some reconfigure benchmarks, and on a Pi4 get ~2.5usec to reconfigure to input and ~3.5usec to reconfigure to output.  So much quicker than the initial request and in the same ballpark as performing a get/set value.
