### ISSUE TITLE
Error autodetecting v1

### ISSUE THREAD

**Issue by fpagliughi** [warthog618/gpiocdev-rs#2]
I'm testing out v1 support with a BeagleBone Green (Debian 10, Linux 4.19). 

When I build with both ABI v1 & v2 compiled in and try the `watcher` example, I get an error:
```
$ ./watcher 
Error: Failed to request line

Caused by:
    0: uAPI get_line returned: Invalid argument
    1: Invalid argument
```

When I build with _only_ ABI v1, it works:
```
$ ./watcher 
EdgeEvent { timestamp_ns: 1684116488534838032, kind: Rising, offset: 23, seqno: 0, line_seqno: 0 }
EdgeEvent { timestamp_ns: 1684116489135030032, kind: Falling, offset: 23, seqno: 0, line_seqno: 0 }
EdgeEvent { timestamp_ns: 1684116493071497949, kind: Rising, offset: 23, seqno: 0, line_seqno: 0 }
...
```

The lib README claims if built with both, it will auto-detect and use the proper v1.

I wrote a little test app to show the result of calling `detect_abi_version()`, with both enabled, and it reports the right result of v1.
```
$ ./gpioabi 
GPIO ABI: uAPI ABI v1
```

To build with both, I'm using `cross` like this:
```
$ cross build --target armv7-unknown-linux-gnueabihf --features="uapi_v1" --examples --release
```

**Comment by warthog618** [comment]
Yeah, that is a bug.  The chip should detect the ABI during construction but is just defaulting to v2.

I'll have to build an old kernel to test on.

Does it work for you if you pass `.using_abi_version(AbiVersion::V1)` to the builder?  That would demonstrate that everything other than the ABI fallback works.

**Comment by warthog618** [comment]
Turns out it wasn't a bug - it was an oversight - I thought I had implemented it but clearly not.
I've pushed a patch  [d892d61] to add fallback to the Builder.  See if that works for you.

That patch is just for the Builder and the requests it creates.  Still thinking about the Chip, which still defaults to uAPI v2.
Currently you can make it auto-detect by calling `chip.using_abi_version(chip.detect_abi_version()?)` before otherwise using it.   
The Chip isn't a major part of the API, the line requests are where most of the action is, so I'm tempted to leave it at that.

**Comment by fpagliughi** [comment]
Hey, thanks for the quick response! Everything worked as you descibed.

> Does it work for you if you pass .using_abi_version(AbiVersion::V1) to the builder?

I tried that first just to check, and it did work. Even better, doing it like this worked:
```
let req = Request::builder()
    .using_abi_version(detect_abi_version()?)
    .on_chip("/dev/gpiochip0")
    ...
```

Then I tried the patch [d892d61](https://github.com/warthog618/gpiocdev-rs/commit/d892d61adfd5f088d36f6fd28395bd5632ed6695) and that worked to detect it automatically.

Nice.

> The Chip isn't a major part of the API, the line requests are where most of the action is, so I'm tempted to leave it at that.

Honestly, if the reqest/builder didn't autodetect and you had to explicitly call `.using_abi_version(detect_abi_version()?)` that would be fine, as long at it was properly documented.

But I think either way you go (auto-detect or not), you should be consistent across the library. If the reqest auto-detects, then the chip should probably auto-detect as well.

**Comment by fpagliughi** [comment]
BTW, overall, very nice job on this whole package.

**Comment by warthog618** [comment]
Thanks - much appreciated - it was my learning Rust project - pick a domain you have some idea about and try to write it in a new language.  Did the same with Go.  I prefer the way the Rust API worked out - it is the best fit to what I had in mind when I wrote the v2 uAPI.

It's been a while since I worked on this, and now you've got me wondering if the `.using_abi_version(detect_abi_version()?)` solution was what I eventually settled on - only to fail to update the docs to match.   But auto-detection is a tad nicer, and definitely what I originally had in mind, so I'll look at adding it to Chip as well.

Whichever way that pans out, not supporting old kernels is not good, so I'll push out an updated crate in the near future - assuming you don't find anything even more critical.

**Comment by fpagliughi** [comment]
Hoo. Not bad for a first timer. I did the same with the Paho MQTT Rust library, and unfortunately, there's still clear evidence of my inexperience throughout it +5yrs later. A complete rewrite wouldn't be a bad idea for me at this point.

Anyway, after thinking about it for an hour or two, perhaps `.using_abi_version(detect_abi_version()?)` for both is the better way to go? It would certainly be more explicit which wouldn't be a bad idea. It might be less confusing to apps that think they have a v2 connection, but actually had it secretly downgraded to v1 without any notice.

I would just make a few recommendations:
- Fix the docs :-)
- Show the usage in the docs and/or a few examples. It'll be common for people to need v1 for a while yet. A lot of popular maker boards are still shipping 4.x kernels.
- Consider if there's a better way to report the error. I know this might be difficult, but seeing something like "Unsupported uAPI v2" might be more helpful than "Invalid Argument."

**Comment by warthog618** [comment]
> Hoo. Not bad for a first timer. I did the same with the Paho MQTT Rust library, and unfortunately, there's still clear evidence of my inexperience throughout it +5yrs later. A complete rewrite wouldn't be a bad idea for me at this point.
> 

Cool, I'll have to take a look.

Fortunately for me I was late to the party so there was a lot more examples to learn from.

> Anyway, after thinking about it for an hour or two, perhaps `.using_abi_version(detect_abi_version()?)` for both is the better way to go? It would certainly be more explicit which wouldn't be a bad idea. It might be less confusing to apps that think they have a v2 connection, but actually had it secretly downgraded to v1 without any notice.
> 

I generally agree that explicit is best, and that being clever behind the scenes is probably going to come back and bite you.

But I think it makes sense here.  The point is that in general apps shouldn't care.
If they really do care then there are methods for them to check what ABI they are actually using.
And if they do want v2 features and get a v1 kernel then they will get appropriate errors (more on that below).

To be clear, there is no "being secretly downgraded".  Either the op is 100% equivalent in v1 and v2, or it uses a feature not supported by the v1 ABI and you will get an appropriate error.

> I would just make a few recommendations:
> 
>     * Fix the docs :-)
> 

Once auto-detect is in they will be correct again, but yeah I'll have to do a complete review sometime.

>     * Show the usage in the docs and/or a few examples. It'll be common for people to need v1 for a while yet. A lot of popular maker boards are still shipping 4.x kernels.
> 

Tough to show auto-detect in examples (the whole point is you don't see it ;-), but for the explicit cases sure.
It is done explicitly in the cli tools (checkout chip_from_path a the top of cli/src/common.rs) - you can force them to use a particular ABI when built with both.  But not the most accessible examples, and I agree that working examples are best demonstrator so I'll look at adding more.

>     * Consider if there's a better way to report the error. I know this might be difficult, but seeing something like "Unsupported uAPI v2" might be more helpful than "Invalid Argument."

It does - given the supported ABI is known.
The underlying issue being the kernel doesn't distinguish between an unsupported ioctl and an error on the params to an ioctl - both cases return EINVAL.
So the library can't tell if there is something wrong with the request or if the ioctl isn't even supported.
(the detect_abi_version probing uses a known good ioctl (line info of offset 0) that will always work on any chip)
Instead, the library does validation prior to the request, rejects any request that can't be performed by the selected ABI, and reports an appropriate error if if can't be. e.g. if you attempt to use a v2 feature using the v1 ABI.

That does not completely rule out an ioctl returning EINVAL, but that should only happen if v2 and the library are extended with new features and you try to use those on an older v2 kernel.  The HTE event clock feature springs to mind.  Oh, or if you use some of the later v1 features on a really old kernel.  e.g. the bias feature.

Note that v2 is effectively a complete superset of v1, so all v1 operations can be mapped to v2, so the only case we need to be concerned with is users trying to use v2 features on a v1 kernel.

If you force an unsupported ABI (what was effectively happening when it was defaulting to v2 without the auto-detect) then the library can't determine the cause. Unless it was to double check the supported ABI version on every ioctl error.
And I don't really want to go there.

With auto-detect you will ALWAYS be using a supported ABI, so I'm thinking that is the way to go for the average user.
If you force it away from that then that is on you, and again there are functions available for the user to check support.

I have an implementation of auto-detect for Chip now.  It actually turned out neater than the Builder solution.
Just need find some time to test it before I push it.

**Comment by fpagliughi** [comment]
> Just need find some time to test it before I push it.

If you push a branch, I can test it. I’m at a conference the rest of this week without any hardware, but can try it when I get back.

I’m also going to try converting a sizable controller app from _gpio-cdev_ to this library and move it to _async-io_. It will use much of the API, so should be a good test of a lot of the features.

**Comment by warthog618** [comment]
Thanks, but I should be good - building an old kernel to do some testing on at the moment.
All going well I'll have that sorted before the weekend, and publish an updated crate soon after that.

But that reminds me - I need to instrument-coverage to see what I've missed in the test suite.
I think the coverage is pretty good, but I do need to check.
And more testing in different environments is always welcome.

**Comment by fpagliughi** [comment]
That all sounds awesome. The app I have needs to run on old kernels and new. It was written before v2, so will continue to adhere to the v1 subset for all the kernels, but eventually may take advantage of v2, if available. Overall should be a good test of the library.

**Comment by warthog618** [comment]
auto-detect for Chip is now in master, as is a change to the cli tools to expose `--abi-version` when both uAPIs are built (which is the default for the cli).  Previously that option was present but hidden (well strictly it was `--abiv`).

Wrt the cli, I also intend to expose a function to report what uAPI versions are available (still thinking what such a command would look like) and add an explicit check that the selected version is supported before performing any other actions (trying to think of any case where you might not want that before committing to it).

**Comment by warthog618** [comment]
I've pushed those cli changes.

The cli now explicitly checks if the kernel supports the ABI you select with ```--abi-version``` before trying to perform any other commands.

The new command is called "platform" and looks like:

```shell
$ gpiocdev platform
Kernel 5.4.237-yocto-standard
uAPI ABI v1 is supported.
uAPI ABI v2 is not supported by the kernel.
```
The ```--verbose``` option gives a little more detail wrt uAPI features:
```shell
$ gpiocdev platform -v
Kernel 5.4.237-yocto-standard
Kernel does not support bias or reconfigure (added in 5.5).
uAPI ABI v1 is supported.
uAPI ABI v2 is not supported by the kernel.
```

**Comment by fpagliughi** [comment]
Nice.

**Comment by warthog618** [comment]
You good with those fixes?  If so I plan to tag and publish updated crates to crates.io, then move on to your serde PR.

**Comment by fpagliughi** [comment]
Yeah. Go for it. We can close this.
