### ISSUE TITLE
Docs for v0.4.3 didn't build on docs.rs

### ISSUE THREAD

**Issue by fpagliughi** [warthog618/gpiocdev-rs#5]
If you go to the project page on [crates.io](https://crates.io/crates/gpiocdev), there is no link to the documentation for the library.

If you click through the links of a build error, it seems to be some problem with the nightly compiler, v1.71.0-nightly:
https://docs.rs/crate/gpiocdev/0.4.3/builds/824861

I got there from here:
https://docs.rs/crate/gpiocdev/latest

**Comment by warthog618** [comment]
Well that is damn stupid.
They build fine locally with 1.70.
Wtf are they doing using nightly for docs?
And why didn't it complain when the crate was published?

And the errors appear to be from the value-bag crate, so I don't see how I can fix that.
Remove whatever dependency pulls it in??

**Comment by warthog618** [comment]
Looks like an issue with docs.rs to me - their build pulled in value-bag v1.0.0-alpha.9, when the latest is 1.4.0 - which is what I get when I build, including with the latest nightly.
docs.rs doesn't seem to have a convenient way to trigger a rebuild - need to raise an issue or push a crate update and see if that fixes it.  Neither option is good.

**Comment by warthog618** [comment]
Pulled docs.rs and did a local build of the documents in the docs.rs build environment and that also works fine.
So definitely some issue related to the docs.rs that was live at the time gpiocdev 0.4.3 was published.

Raised an [issue](https://github.com/rust-lang/docs.rs/issues/2143) with docs.rs, who triggered a rebuild that succeeded. Seems they had a stale value-bag when docs-rs was deployed, but they've since fixed it.

**Comment by fpagliughi** [comment]
Oh, nice. Yeah the doc link is now up on crates.io.
Awesome.
